### ISSUE TITLE
NullReference thrown at Application's Main method after updating to version 2.1.1

### ISSUE THREAD

**Issue by chris247474** [keannan5390/Xamarin.Plugin.FAB#2]
@keannan5390 first of all, great work on this nuget. It's been really useful for my PCL projects. However, after updating to 2.1.1 I get the following exception (image attached). When I expand the stack trace, none of my own code shows up and I don't recognise anything except the FAB related exception. I haven't changed anything else in my solution, except for this update.  

I tried updating Xamarin Forms to every version >= 2.1.0.6529. I still get the same error, unless I downgrade FAB.Forms to 1.0.0.1, which works perfectly. 

Has anyone else come across this? Thanks!

<img width="605" alt="fab nullreferenceexception" src="https://cloud.githubusercontent.com/assets/16344192/16574578/12541fb0-42b3-11e6-9f2c-aae97ff90c55.png">

**Comment by sidNee** [comment]
same issue....@keannan5390: please Create a new solution and load your Fab.forms package and tell us if it works for you..... :(

My settup:
New Forms Project with iOS and Android with Fab.Forms 2.1.1.
Additional in the iOS AppDelegate.cs the Line FAB.iOS.FloatingActionButtonRenderer.InitControl();

Android Yeah...iOS NullReferences like chrisdavetv

**Comment by matsnas** [comment]
I also get a nullref exception as christdavetv, but on Android! Works fine on ios?! Using FAB.Form 2.1.1 and Xamarin.Forms 2.3.0.107.

Stack trace:
`at Xamarin.Forms.Platform.Android.Platform.Xamarin.Forms.Platform.Android.IPlatformLayout.OnLayout (Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b) [0x000a7] in C:\BuildAgent\work\aad494dc9bc9783\Xamarin.Forms.Platform.Android\Platform.cs:1017 
  at Xamarin.Forms.Platform.Android.PlatformRenderer.OnLayout (Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b) [0x0000e] in C:\BuildAgent\work\aad494dc9bc9783\Xamarin.Forms.Platform.Android\PlatformRenderer.cs:73 
  at Android.Views.ViewGroup.n_OnLayout_ZIIII (IntPtr jnienv, IntPtr native__this, Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b) [0x00009] in /Users/builder/data/lanes/3540/1cf254db/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Views.ViewGroup.cs:3427 
  at (wrapper dynamic-method) System.Object:26f7d825-62c3-4847-9749-aad0b02eca66 (intptr,intptr,bool,int,int,int,int)`

**Comment by ghost** [comment]
i'm starting to take a look at this. sorry for the delay.

**Comment by ghost** [comment]
@chrisdavetv @sidNee @matsnas It looks like this a result of not subclassing from FormsApplicationActivity in your main activity. The library now uses the AppCompat variation rather than an internal class for the Floating Android Button and as such, you need to use the AppCompat friendly Xamarin.Forms activity.

``` c-sharp
public class MainActivity : FormsAppCompatActivity
{
        protected override void OnCreate (Bundle savedInstanceState)
        {
            FormsAppCompatActivity.ToolbarResource = Resource.Layout.toolbar;
            FormsAppCompatActivity.TabLayoutResource = Resource.Layout.tabs;

            base.OnCreate (savedInstanceState);

            Xamarin.Forms.Forms.Init (this, savedInstanceState);

            this.LoadApplication (new App ());
       }
}
```

Try that, and if it still doesn't work for you after that let me know and I can look into it more.

**Comment by sidNee** [comment]
@keannan5390

Thank you for replying.

The problem for me is ios not android.

**Comment by chris247474** [comment]
@keannan5390 

Yes same for me. iOS is throwing the exception, not Android. 

In my AppDelegate.cs, I'm inheriting from XLabs.Forms.XFormsApplicationDelegate (since I use CircleImages), which in turn inherits from the original Xamarin.Forms.Platform.iOS.FormsApplicationDelegate.  I'll try switching back and I'll let you know if it fixes the problem. 

@sidNee, in your situation, are you inheriting directly from Xamarin.Forms.Platform.iOS.FormsApplicationDelegate?

**Comment by sidNee** [comment]
@chrisdavetv I only inheriting from Xamarin.Forms....this is a new projekt

**Comment by ghost** [comment]
@sidNee @chrisdavetv whoops, sorry about that. Ok, I'll look into it some more.

**Comment by ghost** [comment]
@sidNee @chrisdavetv this is fixed for iOS & available in the 2.1.2-pre3 package. I need to do some final testing, but it should be ok.

Once verified, it'll be available in the 2.1.2 stable version.

**Comment by LuigiMaestrelli** [comment]
@keannan5390 

I'm using the 2.1.2-pre3 version and I'm still getting this issue on Android.
Tested with Android 4 to 7.

```
[0:] Object reference not set to an instance of an object.
[0:]   at FAB.Droid.FloatingActionButtonRenderer+<SetImage>c__async6+<SetImage>c__AnonStorey7.<>m__0 () [0x00010] in <865ebf9a4258496ba3806c92ae441acc>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Java.Lang.IRunnable.cs:81 
  at (wrapper dynamic-method) System.Object:751c37f4-1b42-4db4-90e4-d0137600522b (intptr,intptr)
An unhandled exception occured.
```

When this happens the app freezes completely
